export const COURSE_META = {
  id: 'searchquest-suchmaschinen-v1',
  title: 'Wie Suchmaschinen funktionieren',
  subtitle: 'Crawling · Indexierung · Relevanz · Ranking · SEO',
  caseTitle: 'UrbanStep bringt den RainStep One auf den Markt',
  caseText: 'Du arbeitest im E-Commerce-Team von UrbanStep. Das Unternehmen bringt den neuen wasserdichten Sneaker „RainStep One“ heraus. Die Produktseite ist online – aber wie schafft es UrbanStep, bei einer passenden Google-Suche überhaupt gefunden zu werden? Im Kurs verfolgst du den Weg der Seite vom ersten Link bis zur Suchergebnisliste und entwickelst am Ende einen fundierten Search-Launch-Plan.'
};

export const SHOP_ITEMS = [
  { id:'bg-sky', kind:'background', label:'Search Sky', icon:'☁️', threshold:100, value:'sky' },
  { id:'avatar-scout', kind:'avatar', label:'Web-Scout', icon:'🧭', threshold:180, value:'🧭' },
  { id:'pet-spider', kind:'pet', label:'Crawler-Spinne', icon:'🕷️', threshold:260, value:'🕷️' },
  { id:'bg-mint', kind:'background', label:'Index Mint', icon:'🌿', threshold:340, value:'mint' },
  { id:'avatar-robot', kind:'avatar', label:'Crawler-Bot', icon:'🤖', threshold:440, value:'🤖' },
  { id:'pet-owl', kind:'pet', label:'Ranking-Eule', icon:'🦉', threshold:560, value:'🦉' },
  { id:'bg-sunset', kind:'background', label:'SERP Sunset', icon:'🌅', threshold:680, value:'sunset' },
  { id:'avatar-detective', kind:'avatar', label:'SEO-Detektiv', icon:'🕵️', threshold:800, value:'🕵️' },
  { id:'pet-rabbit', kind:'pet', label:'Link-Hase', icon:'🐇', threshold:920, value:'🐇' },
  { id:'bg-night', kind:'background', label:'Crawler Night', icon:'🌙', threshold:1040, value:'night' },
  { id:'avatar-ninja', kind:'avatar', label:'Search-Ninja', icon:'🥷', threshold:1180, value:'🥷' },
  { id:'pet-dragon', kind:'pet', label:'Index-Drache', icon:'🐉', threshold:1320, value:'🐉' },
  { id:'bg-lavender', kind:'background', label:'Ranking Lavender', icon:'🪻', threshold:1450, value:'lavender' },
  { id:'avatar-rocket', kind:'avatar', label:'Launch-Profi', icon:'🚀', threshold:1580, value:'🚀' },
  { id:'pet-unicorn', kind:'pet', label:'SEO-Einhorn', icon:'🦄', threshold:1710, value:'🦄' },
  { id:'bg-ice', kind:'background', label:'Search Ice', icon:'❄️', threshold:1820, value:'ice' }
];

const T=(id,section,title,type,prompt,xp,extra={})=>({id,section,title,type,prompt,xp,...extra});

export const SECTIONS = [
  {
    id:'start', nav:'Start', icon:'👟', title:'Mission Start: Wird UrbanStep überhaupt gefunden?', kicker:'Vom neuen Produkt zur Suchergebnisliste',
    content:`
      <div class="hero-case search-hero">
        <img class="hero-illustration" src="/assets/rainstep.svg" alt="Illustration des fiktiven Sneakers RainStep One">
        <div><span class="eyebrow">Beispielfall</span><h3>UrbanStep launcht den RainStep One</h3>
        <p>UrbanStep ist ein kleiner deutscher Onlineshop. Neu im Sortiment ist der <strong>RainStep One</strong>: ein wasserdichter Sneaker für Alltag und Arbeitsweg. Das Marketingteam möchte Menschen erreichen, die bei Google nach Begriffen wie <strong>„wasserdichte Sneaker nachhaltig“</strong> suchen.</p>
        <div class="product-facts"><span>💧 wasserdicht</span><span>♻️ teilweise recycelte Materialien</span><span>🛒 nur im eigenen Onlineshop</span></div></div>
      </div>
      <div class="plenum-card"><span class="card-icon">🗣️</span><div><span class="eyebrow">Stopp · Plenumsfrage</span><h3>Die Produktseite ist online. Was muss passieren, damit Google sie findet – und warum könnte UrbanStep später weiter oben oder weiter unten erscheinen?</h3><p>Sammelt zunächst Vermutungen. Noch nicht nachschlagen: Entscheidend ist, welche Schritte ihr euch logisch vorstellen könnt.</p></div></div>
      <div class="concept-grid three">
        <div class="question-card"><span>1</span><h4>Entdecken</h4><p>Wie erfährt Google, dass die neue Produktseite existiert?</p></div>
        <div class="question-card"><span>2</span><h4>Verarbeiten</h4><p>Welche Informationen versteht und speichert die Suchmaschine?</p></div>
        <div class="question-card"><span>3</span><h4>Ordnen</h4><p>Warum steht eine passende Seite vor einer anderen?</p></div>
      </div>
      <div class="definition-card"><div class="definition-label">Definition · Suchmaschine</div><p>Eine <strong>Suchmaschine</strong> ist ein Informationssystem, das Inhalte auffindbar macht. Dazu werden Inhalte automatisiert <strong>entdeckt</strong>, <strong>verarbeitet</strong> und in einem <strong>Index</strong> organisiert. Bei einer Suchanfrage werden passende Inhalte ausgewählt und geordnet.</p></div>
      <div class="flow-diagram big" aria-label="Gesamtprozess einer Suchmaschine">
        <div class="flow-node">🌐 Web<br><small>Seiten existieren</small></div><div class="flow-arrow">→</div>
        <div class="flow-node">🕷️ Crawling<br><small>Seiten entdecken</small></div><div class="flow-arrow">→</div>
        <div class="flow-node">🗂️ Indexierung<br><small>Inhalte verarbeiten</small></div><div class="flow-arrow">→</div>
        <div class="flow-node">🔎 Suchanfrage<br><small>passende Seiten</small></div><div class="flow-arrow">→</div>
        <div class="flow-node">🏁 Ranking<br><small>Ergebnisse ordnen</small></div>
      </div>
      <div class="info-note"><strong>Wichtig:</strong> Organische Suchergebnisse und bezahlte Anzeigen sind nicht dasselbe. Google erklärt ausdrücklich, dass man sich durch Bezahlung weder häufigeres Crawling noch ein höheres <strong>organisches</strong> Ranking kaufen kann.</div>
      <div class="source-row"><a class="source-link" href="https://developers.google.com/search/docs/fundamentals/how-search-works?hl=de" target="_blank" rel="noopener">📚 Google Search Central: Funktionsweise der Google Suche</a></div>`,
    tasks:[
      T('start-1','start','Drei Kernphasen','single','Welche Reihenfolge beschreibt den grundlegenden Weg einer Webseite zur Suchergebnisliste am besten?',20,{options:[['a','Ranking → Crawling → Indexierung'],['b','Crawling → Indexierung → Bereitstellung/Ranking'],['c','Indexierung → Werbung → Crawling'],['d','Suchanfrage → Crawling → Website erstellen']],correct:'b',solution:'Crawling → Indexierung → Bereitstellung/Ranking.',explanation:'Zuerst muss eine Seite entdeckt und abgerufen werden, anschließend werden ihre Inhalte verarbeitet. Erst bei einer Suchanfrage werden passende Ergebnisse ausgewählt und geordnet.'}),
      T('start-2','start','Organisch oder bezahlt?','boolean','Ein Unternehmen kann Google bezahlen, damit seine Produktseite im organischen Ranking dauerhaft höher eingestuft wird.',20,{correct:false,solution:'Falsch. Bezahlte Anzeigen und organische Rankings sind getrennte Bereiche.',explanation:'Google gibt an, keine Zahlungen anzunehmen, um Seiten häufiger zu crawlen oder organisch höher zu ranken.'}),
      T('start-3','start','UrbanSteps offene Fragen','matching','Ordne die Frage dem passenden Suchmaschinenprozess zu.',30,{pairs:[['Wie entdeckt Google die RainStep-Seite?','Crawling'],['Wie verarbeitet Google Inhalt, Titel und Bilder?','Indexierung'],['Welche Seiten passen zu „wasserdichte Sneaker“?','Relevanzbestimmung'],['Warum steht Ergebnis A vor Ergebnis B?','Ranking']],solution:'Entdecken → Crawling; Inhalt verarbeiten → Indexierung; Passung zur Suchanfrage → Relevanz; Reihenfolge → Ranking.',explanation:'Die vier Fragen strukturieren den gesamten Kurs.'}),
      T('start-4','start','Prozess sortieren','order','Bringe die Schritte in eine sinnvolle Reihenfolge.',30,{items:[['a','Google ordnet passende Ergebnisse.'],['b','Ein Crawler entdeckt die Seite.'],['c','UrbanStep veröffentlicht eine Produktseite.'],['d','Inhalte werden für den Index verarbeitet.'],['e','Ein Nutzer stellt eine Suchanfrage.']],correct:['c','b','d','e','a'],solution:'Produktseite veröffentlichen → Crawling → Indexierung → Suchanfrage → Ranking.',explanation:'Der Suchindex muss vorbereitet sein, bevor eine Suchanfrage schnell beantwortet werden kann.'}),
      T('start-5','start','Warum nicht das ganze Web neu durchsuchen?','multi','Welche Gründe sprechen dagegen, bei jeder Suchanfrage das gesamte Web neu zu crawlen?',30,{options:[['a','Das Web ist sehr groß.'],['b','Suchergebnisse sollen sehr schnell erscheinen.'],['c','Viele Seiten wären in diesem Moment möglicherweise nicht erreichbar.'],['d','Suchmaschinen dürfen grundsätzlich keine Webseiten speichern.']],correct:['a','b','c'],solution:'Richtig sind a, b und c.',explanation:'Ein vorbereiteter Index ermöglicht schnelle Suche und ist robuster, als bei jeder Anfrage sämtliche Seiten neu abzurufen.'}),
      T('start-6','start','Begriff auswählen','text','Ergänze den Fachbegriff: Die strukturierte Datenbasis, in der eine Suchmaschine Informationen über verarbeitete Webseiten organisiert, heißt …',30,{accepted:['Index','Suchmaschinenindex','Google-Index','Suchindex'],solution:'Index bzw. Suchmaschinenindex.',explanation:'Der Index ist die vorbereitete Datenbasis, in der Informationen über Webseiten organisiert werden.'}),
      T('start-7','start','Erste Hypothese für UrbanStep','free','Formuliere drei begründete Vermutungen, was UrbanStep tun sollte, damit die neue Produktseite von Google gefunden und sinnvoll eingeordnet werden kann.',40,{placeholder:'Formuliere drei Vermutungen und begründe sie jeweils kurz.',solution:'Mögliche sinnvolle Vermutungen: Die Produktseite sollte von bereits auffindbaren Seiten intern verlinkt sein; sie kann in einer Sitemap stehen; der Inhalt sollte klar beschreiben, worum es beim Produkt geht; die Seite sollte technisch erreichbar und mobil gut nutzbar sein. Im Kurs wird geklärt, welche Maßnahmen auf Crawling, Indexierung und Ranking wirken.',criteria:['Du nennst drei konkrete Maßnahmen.','Du begründest jede Maßnahme.','Mindestens eine Maßnahme betrifft Auffindbarkeit und mindestens eine den Inhalt.']}),
      T('start-8','start','Suchmaschine als Informationssystem','free','Erkläre einem neuen Praktikanten bei UrbanStep in eigenen Worten, warum eine Suchmaschine einen Index benötigt.',40,{placeholder:'Erkläre den Zweck des Indexes in zwei bis vier Sätzen.',solution:'Eine Suchmaschine benötigt einen Index, weil sie nicht bei jeder Suchanfrage das gesamte Web neu durchsuchen kann. Gefundene Seiten werden vorher verarbeitet und Informationen darüber strukturiert gespeichert. Dadurch kann die Suchmaschine bei einer Anfrage sehr schnell passende Inhalte auswählen und ordnen.',criteria:['Du erwähnst die vorbereitete Speicherung/Organisation.','Du erklärst den Geschwindigkeitsvorteil.','Du stellst den Bezug zur Suchanfrage her.']}),
      T('start-bonus','start','Bonus: Anzeigen vs. SEO','free','Ein Kollege sagt: „Wenn wir genug Google Ads kaufen, steigen wir automatisch auch im organischen Ranking.“ Beurteile die Aussage.',50,{bonus:true,placeholder:'Beurteile die Aussage und begründe deine Entscheidung.',solution:'Die Aussage ist falsch. Bezahlte Anzeigen und organische Suchergebnisse sind getrennt. Werbung kann Sichtbarkeit kaufen, aber Google erklärt, dass Bezahlung keine höhere organische Rankingposition garantiert oder direkt erkauft.',criteria:['Du trennst Anzeigen und organische Ergebnisse.','Du bewertest die Aussage eindeutig.','Du begründest deine Bewertung.']})
    ]
  },
  {
    id:'crawling', nav:'Crawling', icon:'🕷️', title:'Crawling: Wie entdeckt Google die Produktseite?', kicker:'Links, Sitemaps, Googlebot und Web-Scraping-Abgrenzung',
    content:`
      <div class="context-card"><span class="case-mini">👟 UrbanStep</span><p>Die Adresse <code>urbanstep.example/rainstep-one</code> existiert. Doch im Web gibt es kein zentrales Telefonbuch aller neuen URLs. Eine Suchmaschine muss neue und veränderte Seiten laufend entdecken.</p></div>
      <div class="definition-card"><div class="definition-label">Definition · Web-Crawler</div><p>Ein <strong>Web-Crawler</strong> ist ein automatisiertes Programm, das Webseiten abruft, Inhalte untersucht und <strong>Links zu weiteren Seiten</strong> verfolgt. Der allgemeine Name für Googles Suchcrawler ist <strong>Googlebot</strong>.</p></div>
      <div class="concept-grid two">
        <div class="definition-card"><div class="definition-label">Definition · Link</div><p>Ein <strong>Link</strong> verbindet eine Seite mit einer anderen URL. Für Crawler sind Links wichtige Wege, um weitere Inhalte zu entdecken.</p></div>
        <div class="definition-card"><div class="definition-label">Definition · Sitemap</div><p>Eine <strong>Sitemap</strong> ist eine Datei, in der ein Websitebetreiber Suchmaschinen Informationen über wichtige Seiten und Dateien einer Website bereitstellen kann.</p></div>
      </div>
      <div class="network-card">
        <div class="network-title">So könnte Google den RainStep One entdecken</div>
        <div class="network"><div class="node known">UrbanStep Startseite</div><div class="edge">→</div><div class="node">Sneaker-Kategorie</div><div class="edge">→</div><div class="node target">RainStep One</div></div>
        <div class="network"><div class="node small">Sitemap.xml</div><div class="edge">↗</div><div class="node target">RainStep One</div></div>
        <p class="diagram-caption">Ist eine neue Produktseite sinnvoll intern verlinkt und/oder in einer Sitemap aufgeführt, erhält der Crawler einen Weg zur URL.</p>
      </div>
      <div class="fact-card"><span class="fact-icon">⚡</span><div><span class="eyebrow">Fakt · Wie schnell crawlt Googlebot?</span><h3>Es gibt keine feste globale Seiten-pro-Sekunde-Zahl.</h3><p>Google steuert die Crawlingrate dynamisch. Für die meisten Websites sollte Googlebot im Durchschnitt <strong>nicht häufiger als einmal alle paar Sekunden</strong> zugreifen. Bei leistungsfähigen Websites können mehrere Abrufe parallel auftreten; bei Serverproblemen wird die Last reduziert.</p></div></div>
      <div class="fact-card"><span class="fact-icon">📱</span><div><span class="eyebrow">Fakt · Mobile first</span><h3>Für die meisten Websites crawlt Google überwiegend mit dem Smartphone-Crawler.</h3><p>Google unterscheidet unter anderem <strong>Googlebot Smartphone</strong> und <strong>Googlebot Desktop</strong>. Da die mobile Version für die Indexierung meist im Mittelpunkt steht, kommt die Mehrheit der Crawl-Anfragen typischerweise vom mobilen Crawler.</p></div></div>
      <div class="compare-card"><div><h4>🕷️ Crawling</h4><p><strong>Welche Seiten gibt es?</strong><br>URLs entdecken, aufrufen, Links verfolgen.</p></div><div class="compare-arrow">≠</div><div><h4>🧹 Web Scraping</h4><p><strong>Welche Daten stehen auf einer Seite?</strong><br>Bestimmte Daten wie Preis, Produktname oder Tabellenwerte gezielt auslesen.</p></div></div>
      <div class="info-note"><strong>Kurzbeispiel:</strong> Ein Preisvergleich besucht viele Produktseiten und liest jeweils den Preis aus. Das <strong>Besuchen/Entdecken</strong> der Seiten ist Crawling; das <strong>gezielte Auslesen des Preises</strong> ist Scraping. Ein Programm kann beides kombinieren.</div>
      <div class="info-note"><strong>robots.txt:</strong> Websitebetreiber können Crawlern über Regeln Hinweise geben, welche Bereiche gecrawlt werden sollen oder nicht. Eine robots.txt-Datei ist aber nicht dasselbe wie eine Garantie, dass eine URL niemals in Suchergebnissen auftaucht.</div>
      <div class="source-row"><a class="source-link" href="https://developers.google.com/search/docs/crawling-indexing/googlebot?hl=de" target="_blank" rel="noopener">📚 Googlebot-Dokumentation</a><a class="source-link" href="https://developers.google.com/search/docs/fundamentals/get-started-developers?hl=de" target="_blank" rel="noopener">📚 Suchfreundliche Websites</a></div>`,
    tasks:[
      T('crawl-1','crawling','Crawler definieren','single','Welche Aussage beschreibt einen Web-Crawler am besten?',20,{options:[['a','Ein Crawler bezahlt für Anzeigenplätze.'],['b','Ein Crawler ruft Webseiten automatisiert auf und folgt Links.'],['c','Ein Crawler speichert nur Passwörter.'],['d','Ein Crawler ist eine Liste aller Suchbegriffe.']],correct:'b',solution:'Ein Crawler ruft Webseiten automatisiert auf und folgt Links.',explanation:'So kann er neue oder veränderte Seiten entdecken.'}),
      T('crawl-2','crawling','Crawling oder Scraping?','boolean','Das gezielte Auslesen des Produktpreises aus einer bereits geöffneten Webseite ist typischerweise Web Scraping.',20,{correct:true,solution:'Richtig.',explanation:'Crawling betrifft vor allem das Entdecken/Abrufen von Seiten; Scraping das gezielte Extrahieren bestimmter Daten aus Seiten.'}),
      T('crawl-3','crawling','Wege zur neuen Seite','multi','Welche Maßnahmen können Google helfen, die neue RainStep-Produktseite zu entdecken?',30,{options:[['a','Die Seite wird von der Sneaker-Kategorie verlinkt.'],['b','Die URL steht in einer Sitemap.'],['c','Die Seite ist nur nach Login erreichbar.'],['d','Kein Link führt auf die Seite und die URL wird nirgends genannt.']],correct:['a','b'],solution:'Interne Links und eine Sitemap können die Entdeckung unterstützen.',explanation:'Google kann neue URLs über Links von bekannten Seiten und über Sitemaps entdecken.'}),
      T('crawl-4','crawling','Linknetz erkunden','matching','Ordne die Situation der wahrscheinlichsten Folge zu.',30,{pairs:[['Produktseite ist von der Kategorie verlinkt','Crawler erhält einen Weg zur URL'],['Produktseite ist nur nach Login sichtbar','Crawler kann den Inhalt typischerweise nicht frei abrufen'],['Server liefert wiederholt Fehler','Crawler kann die Zugriffslast reduzieren'],['Neue URL steht in der Sitemap','Suchmaschine erhält einen zusätzlichen Entdeckungshinweis']],solution:'Verlinkung → Weg zur URL; Login → nicht frei abrufbar; Serverfehler → Crawling kann gedrosselt werden; Sitemap → zusätzlicher Entdeckungshinweis.',explanation:'Crawling hängt sowohl von Auffindbarkeit als auch von technischer Erreichbarkeit ab.'}),
      T('crawl-5','crawling','Crawler-Geschwindigkeit','single','Welche Aussage zur Crawling-Geschwindigkeit von Googlebot ist fachlich am treffendsten?',30,{options:[['a','Googlebot ruft jede Website exakt 100-mal pro Sekunde auf.'],['b','Googlebot crawlt jede Website nur einmal pro Monat.'],['c','Die Rate wird dynamisch gesteuert; für die meisten Websites liegt der Durchschnitt nicht häufiger als einmal alle paar Sekunden.'],['d','Die Rate hängt nur davon ab, wie viel Werbung ein Unternehmen kauft.']],correct:'c',solution:'Die Rate wird dynamisch gesteuert.',explanation:'Google versucht, effizient zu crawlen und Websites nicht zu überlasten.'}),
      T('crawl-6','crawling','Entdeckungsprozess','order','Bringe das Beispiel in eine sinnvolle Reihenfolge.',30,{items:[['a','Googlebot folgt dem Link zur Produktseite.'],['b','Die UrbanStep-Kategorieseite ist Google bereits bekannt.'],['c','Die Produktseite kann anschließend verarbeitet werden.'],['d','Auf der Kategorieseite erscheint ein Link zum RainStep One.']],correct:['b','d','a','c'],solution:'Bekannte Kategorieseite → Link erscheint → Googlebot folgt dem Link → Seite kann verarbeitet werden.',explanation:'Links bilden für Crawler Wege durch das Web.'}),
      T('crawl-7','crawling','Problemfall: Orphan Page','free','UrbanStep veröffentlicht die Produktseite, verlinkt sie aber weder intern noch in der Sitemap. Erkläre das Crawling-Problem und schlage zwei sinnvolle Verbesserungen vor.',40,{placeholder:'Beschreibe das Problem und nenne zwei konkrete Verbesserungen.',solution:'Die Seite ist für einen Crawler schwerer zu entdecken, weil kein bekannter Linkpfad auf sie führt und die Sitemap keinen Hinweis liefert. UrbanStep sollte die Seite z. B. von der Kategorie oder Startseite intern verlinken und die URL in die Sitemap aufnehmen.',criteria:['Du erklärst, warum die URL schwerer zu entdecken ist.','Du schlägst zwei sinnvolle Maßnahmen vor.','Mindestens eine Maßnahme nutzt Links oder Sitemap.']}),
      T('crawl-8','crawling','Crawling vs. Scraping im Preisvergleich','free','Ein Preisvergleich besucht Shopseiten, entdeckt neue Produktlinks und speichert anschließend Produktname, Preis und Verfügbarkeit. Trenne die Tätigkeiten fachlich in Crawling und Scraping.',40,{placeholder:'Ordne die Tätigkeiten zu und begründe die Abgrenzung.',solution:'Das Besuchen der Seiten und Folgen neuer Produktlinks ist Crawling. Das gezielte Extrahieren von Produktname, Preis und Verfügbarkeit aus den Seiten ist Scraping. Ein System kann beide Techniken kombinieren.',criteria:['Du ordnest Entdecken/Links dem Crawling zu.','Du ordnest das gezielte Datenauslesen dem Scraping zu.','Du erklärst, dass beide Techniken kombiniert werden können.']}),
      T('crawl-bonus','crawling','Bonus: Warum nicht maximal schnell?','free','Warum wäre es problematisch, wenn ein Crawler eine kleine Shopseite ohne Rücksicht auf deren Serverleistung tausendfach pro Sekunde abrufen würde?',50,{bonus:true,placeholder:'Erkläre mindestens zwei mögliche Probleme.',solution:'Eine sehr hohe Abrufrate könnte den Server stark belasten, legitime Nutzer ausbremsen oder Fehler verursachen. Deshalb passen professionelle Crawler die Zugriffslast an und reagieren auf die Leistungsfähigkeit bzw. Fehlerantworten einer Website.',criteria:['Du nennst eine technische Belastung.','Du beschreibst eine Folge für Nutzer oder Server.','Du stellst den Bezug zur dynamischen Crawlingrate her.']})
    ]
  },
  {
    id:'indexing', nav:'Indexierung', icon:'🗂️', title:'Indexierung: Was speichert eine Suchmaschine über Seiten?', kicker:'Inhalte analysieren, Duplikate erkennen und Informationen strukturieren',
    content:`
      <div class="definition-card"><div class="definition-label">Definition · Indexierung</div><p>Bei der <strong>Indexierung</strong> verarbeitet und analysiert die Suchmaschine eine gecrawlte Seite. Dabei versucht sie zu verstehen, <strong>worum es auf der Seite geht</strong> und welche Informationen für spätere Suchanfragen relevant sein könnten.</p></div>
      <div class="definition-card"><div class="definition-label">Definition · Suchmaschinenindex</div><p>Ein <strong>Suchmaschinenindex</strong> ist eine große, strukturierte Datenbasis mit Informationen über verarbeitete Webseiten. Bei einer Suchanfrage wird überwiegend dieser vorbereitete Datenbestand durchsucht – nicht das gesamte Web neu gecrawlt.</p></div>
      <div class="plenum-card"><span class="card-icon">🤔</span><div><span class="eyebrow">Gemeinsam klären</span><h3>Wie viele „Indizes“ werden für eine Website gespeichert?</h3><p>Die Vorstellung „eine Website bekommt 15 Indizes“ ist irreführend. Suchmaschinen veröffentlichen kein vollständiges internes Datenbankschema. Eine Website kann aus vielen einzelnen URLs bestehen, die jeweils verarbeitet werden. Dabei werden viele <strong>Signale und Inhaltsmerkmale</strong> analysiert – aber es gibt keine öffentlich bekannte feste Anzahl von „Indexfeldern pro Website“.</p></div></div>
      <div class="index-pipeline">
        <div class="pipeline-step"><span>1</span><b>Seite abrufen</b><small>HTML, Bilder, ggf. JavaScript</small></div>
        <div class="pipeline-arrow">→</div>
        <div class="pipeline-step"><span>2</span><b>Inhalt analysieren</b><small>Text, Titel, Bilder, Alt-Texte …</small></div>
        <div class="pipeline-arrow">→</div>
        <div class="pipeline-step"><span>3</span><b>Duplikate prüfen</b><small>kanonische URL bestimmen</small></div>
        <div class="pipeline-arrow">→</div>
        <div class="pipeline-step"><span>4</span><b>Informationen organisieren</b><small>für spätere Suchanfragen</small></div>
      </div>
      <div class="real-world-card"><div><span class="eyebrow">Reales Beispiel · IKEA</span><h3>KALLAX Produktseite</h3><p>Eine öffentlich zugängliche IKEA-Produktseite enthält z. B. <strong>Produktname, Preis, Farbe, Maße, Produktbeschreibung, Bilder und Bewertungen</strong>. Solche sichtbaren Informationen können einer Suchmaschine helfen, die Seite thematisch einzuordnen.</p><p><strong>Wichtig:</strong> Von außen können wir nicht behaupten, dass Google genau diese Angaben als feste Datenbankfelder speichert. Googles öffentlich dokumentierter Indexierungsprozess analysiert u. a. Textinhalte, wichtige HTML-Tags und Attribute sowie Bilder und Videos.</p><a class="tool-link" href="https://www.ikea.com/de/de/p/kallax-regal-weiss-30372188/" target="_blank" rel="noopener">🔗 Reale KALLAX-Seite öffnen</a></div><img src="/assets/index-card.svg" alt="Illustration einer Produktseite mit strukturierten Informationsfeldern"></div>
      <div class="definition-card"><div class="definition-label">Definition · kanonische URL</div><p>Wenn sehr ähnliche oder doppelte Inhalte über mehrere URLs erreichbar sind, kann eine Suchmaschine sie gruppieren und eine <strong>kanonische URL</strong> als bevorzugte Version bestimmen.</p></div>
      <div class="warning-note"><strong>Nicht jede gecrawlte Seite wird indexiert.</strong> Technische Sperren, fehlende indexierbare Inhalte, Duplikate oder andere Gründe können dazu führen, dass eine gefundene Seite nicht im Index landet. Eine Indexierung ist auch bei technisch korrekten Seiten nicht garantiert.</div>
      <div class="source-row"><a class="source-link" href="https://developers.google.com/search/docs/fundamentals/how-search-works?hl=de" target="_blank" rel="noopener">📚 Indexierungsprozess bei Google</a><a class="source-link" href="https://developers.google.com/search/docs/crawling-indexing/canonicalization?hl=de" target="_blank" rel="noopener">📚 Kanonische URLs</a></div>`,
    tasks:[
      T('index-1','indexing','Index definieren','single','Was ist ein Suchmaschinenindex?',20,{options:[['a','Eine Liste bezahlter Anzeigen'],['b','Eine strukturierte Datenbasis mit Informationen über verarbeitete Inhalte'],['c','Eine einzelne HTML-Datei pro Internetnutzer'],['d','Der Browsercache eines Schülers']],correct:'b',solution:'Eine strukturierte Datenbasis mit Informationen über verarbeitete Inhalte.',explanation:'Der Index ermöglicht schnelle Auswahl passender Seiten bei einer späteren Suchanfrage.'}),
      T('index-2','indexing','Crawling garantiert Indexierung?','boolean','Wenn Googlebot eine Seite erfolgreich crawlt, ist automatisch garantiert, dass die Seite in den Google-Index aufgenommen wird.',20,{correct:false,solution:'Falsch. Crawling und Indexierung sind unterschiedliche Schritte; Indexierung ist nicht garantiert.',explanation:'Eine Seite kann gefunden und abgerufen werden, ohne später indexiert zu werden.'}),
      T('index-3','indexing','Crawling oder Indexierung?','matching','Ordne die Tätigkeit dem passenden Prozess zu.',30,{pairs:[['Einem Link auf die neue Produktseite folgen','Crawling: Link folgen'],['Text und Seitentitel analysieren','Indexierung: Inhalt analysieren'],['Eine doppelte Seite als Variante erkennen','Indexierung: Duplikate erkennen'],['Eine neue URL in einer Kategorie entdecken','Crawling: URL entdecken']],solution:'Link folgen und URL entdecken → Crawling; Inhalt und Duplikate analysieren → Indexierung.',explanation:'Crawling beschafft Seiten; Indexierung verarbeitet ihre Inhalte.'}),
      T('index-4','indexing','Welche Inhalte helfen beim Verstehen?','multi','Welche öffentlich sichtbaren bzw. dokumentierten Seitenelemente können bei der Indexierung verarbeitet werden?',30,{options:[['a','Textinhalt'],['b','title-Element'],['c','Bilder und zugehörige Informationen'],['d','Das geheime Passwort des Shopbetreibers']],correct:['a','b','c'],solution:'Text, wichtige HTML-Tags/Attribute sowie Bilder und Videos können verarbeitet werden.',explanation:'Private Passwörter gehören selbstverständlich nicht zum öffentlich indexierbaren Seiteninhalt.'}),
      T('index-5','indexing','Indexierungsprozess sortieren','order','Bringe den vereinfachten Prozess in eine sinnvolle Reihenfolge.',30,{items:[['a','Informationen für spätere Suche organisieren'],['b','Seite crawlen/abrufen'],['c','Inhalte analysieren'],['d','mögliche Duplikate bzw. kanonische Version bestimmen']],correct:['b','c','d','a'],solution:'Abrufen → Inhalte analysieren → Duplikate/kanonische Version bestimmen → Informationen organisieren.',explanation:'Indexierung baut auf dem Abruf der Seite auf und strukturiert die gewonnenen Informationen.'}),
      T('index-6','indexing','IKEA-Beispiel','multi','Welche Aussagen zum realen IKEA-Beispiel sind fachlich zulässig?',30,{options:[['a','Die Produktseite zeigt öffentlich Produktname, Preis, Maße und Bewertungen.'],['b','Daraus dürfen wir schließen, dass Google exakt vier feste Indexfelder speichert.'],['c','Die sichtbaren Informationen können helfen, das Seitenthema zu verstehen.'],['d','Das vollständige interne Google-Indexschema ist öffentlich bekannt.']],correct:['a','c'],solution:'Richtig sind a und c.',explanation:'Wir können sichtbare Inhalte beschreiben und dokumentierte Indexierungsprinzipien erklären, aber kein geheimes internes Datenbankschema behaupten.'}),
      T('index-7','indexing','Doppelte Produktseiten','free','UrbanStep hat denselben RainStep One unter zwei fast identischen URLs erreichbar. Erkläre, warum das für die Indexierung ungünstig sein kann und was eine kanonische URL leistet.',40,{placeholder:'Erkläre das Duplikatproblem und die Funktion einer kanonischen URL.',solution:'Sehr ähnliche Inhalte unter mehreren URLs können als Duplikate erkannt werden. Eine kanonische URL bezeichnet die bevorzugte Version, die stellvertretend für die Gruppe ähnlicher Seiten ausgewählt werden kann. Dadurch wird klarer, welche URL als Hauptversion behandelt werden soll.',criteria:['Du beschreibst das Duplikatproblem.','Du erklärst die Funktion der kanonischen URL.','Du beziehst dich auf mehrere URLs mit ähnlichem Inhalt.']}),
      T('index-8','indexing','Warum gibt es keine feste „Indexzahl“?','free','Ein Mitschüler fragt: „Wie viele Indizes speichert Google zu einer Produktseite?“ Formuliere eine fachlich saubere Antwort.',40,{placeholder:'Antworte in drei bis fünf Sätzen und vermeide unbelegte Zahlen.',solution:'Es gibt keine öffentlich bekannte feste Zahl von „Indizes“ oder Indexfeldern pro Webseite. Google spricht von einem großen Suchindex, in dem Informationen über viele Seiten organisiert werden. Bei der Indexierung werden zahlreiche Inhalte und Signale analysiert, das vollständige interne Datenbankschema wird jedoch nicht veröffentlicht. Deshalb sollte man keine konkrete Feldanzahl erfinden.',criteria:['Du verneinst eine unbelegte feste Anzahl.','Du erklärst den Index als große Datenbasis.','Du erwähnst, dass das interne Schema nicht vollständig öffentlich ist.']}),
      T('index-bonus','indexing','Bonus: Login-Seite','free','UrbanStep stellt die Produktbeschreibung versehentlich nur hinter einem Kundenlogin bereit. Welche Folgen kann das für Crawling und Indexierung haben?',50,{bonus:true,placeholder:'Betrachte sowohl Crawling als auch Indexierung.',solution:'Wenn der Inhalt nur nach Login erreichbar ist, kann Googlebot ihn typischerweise nicht wie eine öffentlich zugängliche Seite abrufen. Ohne zugänglichen Inhalt kann die Seite nicht normal verarbeitet und indexiert werden. Für öffentlich auffindbare Produktinformationen sollte die relevante Seite ohne Login zugänglich sein.',criteria:['Du erklärst das Zugriffsproblem.','Du leitest eine Folge für die Indexierung ab.','Du formulierst eine sinnvolle Verbesserung.']})
    ]
  },
  {
    id:'query', nav:'Relevanz', icon:'🔎', title:'Von der Suchanfrage zum passenden Treffer', kicker:'Suchanfrage, Suchabsicht und Relevanz',
    content:`
      <div class="context-card"><span class="case-mini">🔎 Kundenperspektive</span><p>Eine Schülerin sucht auf dem Smartphone nach <strong>„wasserdichte Sneaker nachhaltig“</strong>. Die Suchmaschine muss aus ihrem Index Seiten auswählen, die zu dieser Anfrage besonders gut passen.</p></div>
      <div class="concept-grid two">
        <div class="definition-card"><div class="definition-label">Definition · Suchanfrage</div><p>Eine <strong>Suchanfrage</strong> ist die Eingabe, mit der eine Person einer Suchmaschine ihren Informationsbedarf mitteilt – z. B. Wörter, eine Frage oder eine Produktbezeichnung.</p></div>
        <div class="definition-card"><div class="definition-label">Definition · Relevanz</div><p><strong>Relevanz</strong> beschreibt, wie gut ein Inhalt zu einer konkreten Suchanfrage und dem dahinterliegenden Informationsbedarf passt.</p></div>
      </div>
      <div class="definition-card"><div class="definition-label">Definition · Suchabsicht</div><p>Die <strong>Suchabsicht</strong> ist das Ziel hinter einer Suchanfrage. Menschen können z. B. Informationen suchen, eine bestimmte Website ansteuern, ein Produkt vergleichen oder etwas kaufen wollen.</p></div>
      <div class="search-simulator">
        <div class="search-box">🔎 <b>wasserdichte Sneaker nachhaltig</b></div>
        <div class="search-result best"><span class="result-badge">sehr passend</span><b>RainStep One – wasserdichter Sneaker | UrbanStep</b><p>Wasserdichter Alltagssneaker, Materialinformationen, Größen, Preis und Pflege.</p></div>
        <div class="search-result"><span class="result-badge">teilweise passend</span><b>10 Tipps für trockene Füße im Herbst</b><p>Ratgeber über Regen, Schuhe und Imprägnierung.</p></div>
        <div class="search-result weak"><span class="result-badge">schwach passend</span><b>Geschichte des Sportschuhs</b><p>Historischer Überblick ohne Produktbezug und ohne Wasserdichtigkeit.</p></div>
      </div>
      <div class="think-card"><span class="card-icon">🧠</span><h4>Suchbegriffe allein reichen nicht</h4><p>Eine moderne Suchmaschine versucht nicht nur festzustellen, ob einzelne Wörter vorkommen. Sie bewertet, <strong>wie gut Inhalt und Suchabsicht zusammenpassen</strong>. Eine Seite kann ein Wort enthalten und trotzdem wenig hilfreich sein.</p></div>
      <div class="real-world-strip"><div><span>📍</span><b>Ort</b><small>„Fahrradwerkstatt“ kann lokal unterschiedliche Ergebnisse liefern.</small></div><div><span>🌍</span><b>Sprache</b><small>Die Sprache beeinflusst, welche Inhalte hilfreich sind.</small></div><div><span>📱</span><b>Gerät</b><small>Kontext kann bei der Bereitstellung eine Rolle spielen.</small></div></div>
      <div class="info-note"><strong>Realitätsbezug:</strong> Google beschreibt, dass die Relevanz von vielen Faktoren beeinflusst wird und Ergebnisse je nach Suchanfrage und Kontext unterschiedlich ausfallen können. Das bedeutet nicht, dass wir den vollständigen Algorithmus kennen.</div>
      <div class="source-row"><a class="source-link" href="https://developers.google.com/search/docs/fundamentals/how-search-works?hl=de" target="_blank" rel="noopener">📚 Google: Bereitstellung von Suchergebnissen</a></div>`,
    tasks:[
      T('query-1','query','Relevanz definieren','single','Was bedeutet Relevanz im Kontext einer Suchmaschine?',20,{options:[['a','Wie teuer eine Website ist'],['b','Wie gut ein Inhalt zur Suchanfrage und zum Informationsbedarf passt'],['c','Wie viele Farben die Website verwendet'],['d','Wie oft eine Anzeige gekauft wurde']],correct:'b',solution:'Relevanz beschreibt die Passung zwischen Inhalt und Suchanfrage/Informationsbedarf.',explanation:'Eine relevante Seite beantwortet den konkreten Informationsbedarf möglichst gut.'}),
      T('query-2','query','Suchabsicht','boolean','Zwei Menschen können dieselben Wörter unterschiedlich meinen; deshalb ist die Suchabsicht hinter einer Anfrage wichtig.',20,{correct:true,solution:'Richtig.',explanation:'Suchmaschinen versuchen, nicht nur einzelne Wörter, sondern auch den beabsichtigten Informationsbedarf zu berücksichtigen.'}),
      T('query-3','query','Suchabsichten zuordnen','matching','Ordne die Suchanfrage der wahrscheinlichsten Absicht zu.',30,{pairs:[['„wie Sneaker imprägnieren“','Information suchen'],['„UrbanStep RainStep One“','bestimmtes Produkt/Website finden'],['„wasserdichte Sneaker kaufen“','Kaufabsicht'],['„RainStep One vs. TrailDry X“','Produkte vergleichen']],solution:'Imprägnieren → Information; Produktname → bestimmtes Ziel; kaufen → Kaufabsicht; vs. → Vergleich.',explanation:'Die Suchabsicht hilft zu verstehen, welche Art von Ergebnis nützlich ist.'}),
      T('query-4','query','Treffer auswählen','single','Welche Seite passt am wahrscheinlichsten zur Suche „wasserdichte Sneaker Damen schwarz“?',30,{options:[['a','Allgemeine Geschichte des Turnschuhs'],['b','Produktkategorie mit schwarzen wasserdichten Damen-Sneakern'],['c','Rezept für Schwarzbrot'],['d','Blog über Sommerurlaub am Meer']],correct:'b',solution:'Die Produktkategorie mit schwarzen wasserdichten Damen-Sneakern.',explanation:'Sie deckt Produktart, Eigenschaft, Zielgruppe und Farbe der Suchanfrage ab.'}),
      T('query-5','query','Relevanzsignale','multi','Welche Informationen können helfen zu beurteilen, ob UrbanSteps Seite zur Anfrage „wasserdichte Sneaker nachhaltig“ passt?',30,{options:[['a','Die Produktbeschreibung erklärt Wasserdichtigkeit.'],['b','Materialinformationen beschreiben recycelte Bestandteile.'],['c','Die Seite handelt ausschließlich von Kaffeemaschinen.'],['d','Titel und Überschriften benennen das Produkt klar.']],correct:['a','b','d'],solution:'Richtig sind a, b und d.',explanation:'Inhaltliche Passung und klare Beschreibung helfen Suchsystemen und Nutzern zu verstehen, worum es auf der Seite geht.'}),
      T('query-6','query','Von Anfrage zu Treffern','order','Bringe die Schritte ab Eingabe der Suchanfrage in eine sinnvolle Reihenfolge.',30,{items:[['a','Passende Ergebnisse werden geordnet.'],['b','Nutzer gibt eine Suchanfrage ein.'],['c','Suchsystem sucht im vorbereiteten Index nach passenden Inhalten.'],['d','Ergebnisliste wird angezeigt.']],correct:['b','c','a','d'],solution:'Suchanfrage → Index nach passenden Inhalten durchsuchen → Ergebnisse ordnen → anzeigen.',explanation:'Der Index ermöglicht die schnelle Auswahl relevanter Dokumente.'}),
      T('query-7','query','Gleiche Wörter, andere Absicht','free','Vergleiche die Suchanfragen „Sneaker reinigen“ und „Sneaker kaufen“. Erkläre, warum sinnvolle Suchergebnisse unterschiedlich aussehen sollten.',40,{placeholder:'Vergleiche die Absichten und nenne passende Ergebnisarten.',solution:'„Sneaker reinigen“ hat überwiegend eine Informationsabsicht; sinnvoll wären Anleitungen oder Ratgeber. „Sneaker kaufen“ signalisiert eher eine transaktionale Absicht; Produkt- oder Shopseiten sind passender. Obwohl in beiden Anfragen „Sneaker“ vorkommt, ist der Informationsbedarf unterschiedlich.',criteria:['Du unterscheidest die Suchabsichten.','Du nennst passende Ergebnisarten.','Du erklärst, warum das gleiche Wort nicht zu denselben Ergebnissen führen muss.']}),
      T('query-8','query','UrbanStep und Suchsprache','free','UrbanStep beschreibt den RainStep One nur mit Marketingfloskeln wie „Feel the future“. Die Eigenschaften „wasserdicht“ und „recycelte Materialien“ stehen nirgends im Text. Beurteile das im Hinblick auf Relevanz.',40,{placeholder:'Beurteile, wie gut die Seite zur geplanten Suchanfrage passen dürfte, und begründe.',solution:'Die Seite liefert Suchsystemen und Nutzern wenig klare Information zu den relevanten Eigenschaften. Für Anfragen wie „wasserdichte Sneaker nachhaltig“ ist die inhaltliche Passung schlechter erkennbar. UrbanStep sollte verständliche, tatsächliche Produkteigenschaften klar benennen und erläutern, statt nur vage Werbesprache zu verwenden.',criteria:['Du erkennst das Informationsproblem.','Du stellst den Bezug zur Suchanfrage her.','Du schlägst eine inhaltlich saubere Verbesserung vor.']}),
      T('query-bonus','query','Bonus: Kontextabhängige Suche','free','Warum können zwei Personen bei der Suche nach „Fahrradwerkstatt“ unterschiedliche Ergebnisse erhalten, ohne dass die Suchmaschine deshalb „falsch“ arbeitet?',50,{bonus:true,placeholder:'Nenne mindestens zwei Kontextfaktoren und erkläre ihre Wirkung.',solution:'Bei lokalen Suchanfragen kann der Standort eine wichtige Rolle spielen; außerdem können Sprache und Gerät Kontext liefern. Eine Werkstatt in Leipzig ist für eine Person dort meist hilfreicher als eine Werkstatt in einer weit entfernten Stadt. Unterschiedliche Ergebnisse können daher unterschiedliche Relevanz im jeweiligen Kontext widerspiegeln.',criteria:['Du nennst mindestens zwei Kontextfaktoren.','Du erklärst den Bezug zur Relevanz.','Du vermeidest die Aussage, dass jeder Nutzer immer exakt dieselben Ergebnisse sehen muss.']})
    ]
  },
  {
    id:'ranking', nav:'Ranking', icon:'🏁', title:'Ranking: Warum steht ein Ergebnis vor einem anderen?', kicker:'Viele Signale, unterschiedliche Gewichtung und keine geheime Zauberformel',
    content:`
      <div class="definition-card"><div class="definition-label">Definition · Ranking</div><p>Als <strong>Ranking</strong> bezeichnet man die Reihenfolge, in der Suchergebnisse dargestellt werden. Automatisierte Rankingsysteme bewerten viele Signale, um für eine konkrete Anfrage möglichst hilfreiche Ergebnisse zu ordnen.</p></div>
      <div class="plenum-card"><span class="card-icon">⚖️</span><div><span class="eyebrow">Gemeinsam entscheiden</span><h3>Welche Seite gehört nach oben?</h3><p>Suche: <strong>„wasserdichte Sneaker nachhaltig“</strong>. Seite A erklärt Material, Wasserdichtigkeit, Größen und Pflege. Seite B enthält den Satz „wasserdichte Sneaker“ 30-mal, aber kaum nützliche Produktinformationen. Seite C ist ein allgemeiner Schuhblog von 2018. Diskutiert: Welche Kriterien sind sinnvoll – und welche wären leicht manipulierbar?</p></div></div>
      <div class="signal-grid">
        <div><span>🎯</span><b>Passung</b><p>Wie gut beantwortet der Inhalt die konkrete Suchanfrage?</p></div>
        <div><span>🧾</span><b>Inhaltsqualität</b><p>Ist der Inhalt hilfreich, nachvollziehbar und für Nutzer gemacht?</p></div>
        <div><span>🔗</span><b>Verweise</b><p>Links und andere Signale können bei der Einordnung eine Rolle spielen.</p></div>
        <div><span>📱</span><b>Nutzerfreundlichkeit</b><p>Technische Qualität und Nutzung auf verschiedenen Geräten können relevant sein.</p></div>
        <div><span>🕒</span><b>Aktualität</b><p>Bei manchen Suchanfragen ist Frische wichtiger als bei anderen.</p></div>
        <div><span>🌍</span><b>Kontext</b><p>Ort, Sprache oder Gerät können je nach Anfrage eine Rolle spielen.</p></div>
      </div>
      <div class="info-note"><strong>Keine feste Punkteliste:</strong> Google beschreibt seine Rankingsysteme als Systeme mit vielen Faktoren und Signalen. Die Gewichtung hängt von der Suchanfrage ab. Das vollständige Verfahren ist nicht öffentlich – deshalb sollte niemand behaupten, den exakten „Google-Algorithmus“ zu kennen.</div>
      <div class="fact-card"><span class="fact-icon">⚡</span><div><span class="eyebrow">Fakt</span><h3>Die Auswahl aus sehr großen Datenmengen geschieht in Sekundenbruchteilen.</h3><p>Google beschreibt Rankingsysteme, die Informationen aus sehr großen Beständen automatisiert auswerten, um relevante und hilfreiche Ergebnisse bereitzustellen.</p></div></div>
      <div class="compare-card"><div><h4>✅ Sinnvolle Optimierung</h4><p>hilfreiche Inhalte, klare Struktur, gute Technik, echte Produktinformationen</p></div><div class="compare-arrow">vs.</div><div><h4>🚫 Manipulationsversuch</h4><p>unnatürliche Wiederholungen, irreführende Inhalte oder andere Spam-Taktiken</p></div></div>
      <div class="source-row"><a class="source-link" href="https://developers.google.com/search/docs/appearance/ranking-systems-guide" target="_blank" rel="noopener">📚 Google: Ranking-Systeme</a><a class="source-link" href="https://developers.google.com/search/docs/essentials?hl=de" target="_blank" rel="noopener">📚 Google Search Essentials</a></div>`,
    tasks:[
      T('rank-1','ranking','Ranking definieren','single','Was bedeutet Ranking?',20,{options:[['a','Das Speichern eines Passworts'],['b','Die Reihenfolge der Suchergebnisse'],['c','Das Erstellen einer Sitemap'],['d','Das Laden eines Produktbildes']],correct:'b',solution:'Ranking ist die Reihenfolge der Suchergebnisse.',explanation:'Rankingsysteme ordnen passende Ergebnisse für eine konkrete Anfrage.'}),
      T('rank-2','ranking','Ein Faktor für alle Suchen?','boolean','Bei jeder Suchanfrage werden alle Rankingfaktoren immer exakt gleich gewichtet.',20,{correct:false,solution:'Falsch.',explanation:'Die Bedeutung von Signalen kann sich je nach Suchanfrage unterscheiden; bei aktuellen Ereignissen kann z. B. Aktualität wichtiger sein als bei zeitlosen Themen.'}),
      T('rank-3','ranking','Signal und Situation','matching','Ordne die Situation dem naheliegenden Aspekt zu.',30,{pairs:[['Suche nach „Wahlergebnis heute“','Aktualität'],['Suche nach „Fahrradwerkstatt in meiner Nähe“','Standortkontext'],['Produktseite lädt auf dem Smartphone sauber','Nutzerfreundlichkeit'],['Seite beantwortet exakt die Produktfrage','inhaltliche Passung']],solution:'Heute → Aktualität; in meiner Nähe → Standort; mobile Darstellung → Nutzerfreundlichkeit; genaue Antwort → Passung.',explanation:'Je nach Suchanfrage können unterschiedliche Aspekte besonders relevant sein.'}),
      T('rank-4','ranking','Hilfreich oder Keyword-Stuffing?','single','Welche Variante ist für Nutzer und Suchsysteme voraussichtlich hilfreicher?',30,{options:[['a','Eine Produktseite mit verständlicher Beschreibung, Materialdetails, Größen und Pflegehinweisen'],['b','Eine Seite, die denselben Suchbegriff 100-mal ohne Mehrwert wiederholt'],['c','Eine leere Seite mit nur dem Produktfoto'],['d','Eine Seite mit irreführendem Titel und anderem Inhalt']],correct:'a',solution:'Die verständliche, informative Produktseite.',explanation:'Hilfreicher Inhalt unterstützt Nutzer und entspricht eher sinnvollen SEO-Grundsätzen als bloße Keyword-Wiederholung.'}),
      T('rank-5','ranking','Ranking-Aussagen prüfen','multi','Welche Aussagen sind fachlich angemessen?',30,{options:[['a','Das vollständige Rankingverfahren ist nicht öffentlich.'],['b','Eine einzelne Maßnahme garantiert immer Platz 1.'],['c','Relevanz und Nutzerkontext können eine Rolle spielen.'],['d','Die Gewichtung von Signalen kann je nach Anfrage variieren.']],correct:['a','c','d'],solution:'Richtig sind a, c und d.',explanation:'Es gibt keine öffentlich bekannte einfache Formel, die eine Spitzenposition garantiert.'}),
      T('rank-6','ranking','Rankingentscheidung','order','Ordne die Ergebnisse für die Suche „RainStep One Pflege wasserdicht“ nach plausibler inhaltlicher Passung – von stark nach schwach.',30,{items:[['a','UrbanStep-Pflegeanleitung für RainStep One'],['b','Allgemeine Seite über Sportschuhgeschichte'],['c','Produktseite RainStep One mit Pflegeabschnitt'],['d','Kochrezept']],correct:['a','c','b','d'],solution:'Pflegeanleitung → Produktseite mit Pflegeabschnitt → allgemeine Sportschuhgeschichte → Kochrezept.',explanation:'Je genauer Inhalt und Suchabsicht zusammenpassen, desto plausibler ist die Relevanz.'}),
      T('rank-7','ranking','Keine Ranking-Garantie','free','Ein SEO-Dienstleister verspricht UrbanStep: „Mit unserem Trick seid ihr garantiert in einer Woche auf Platz 1.“ Beurteile diese Aussage fachlich.',40,{placeholder:'Beurteile die Garantie und begründe sie mit dem Funktionsprinzip von Rankingsystemen.',solution:'Eine solche Garantie ist unseriös. Rankings entstehen aus vielen Signalen, deren Gewichtung je nach Suchanfrage variieren kann; das vollständige Verfahren ist nicht öffentlich. Außerdem konkurrieren andere Seiten um dieselben Anfragen und Suchsysteme verändern sich. Seriöse SEO kann Auffindbarkeit und Qualität verbessern, aber keinen festen Platz garantieren.',criteria:['Du bewertest die Garantie kritisch.','Du nennst mehrere Einflussfaktoren bzw. die fehlende vollständige Transparenz.','Du unterscheidest Verbesserung von garantierter Position.']}),
      T('rank-8','ranking','Aktualität abwägen','free','Vergleiche die Suchanfragen „Wie funktioniert Photosynthese?“ und „Bundesliga Ergebnis heute“. Warum kann Aktualität beim Ranking unterschiedlich wichtig sein?',40,{placeholder:'Vergleiche die Informationsbedürfnisse und erkläre die Rolle der Aktualität.',solution:'Photosynthese ist ein weitgehend zeitloses Fachthema; ein guter älterer Erklärtext kann weiterhin nützlich sein. Bei „Bundesliga Ergebnis heute“ ist die zeitliche Aktualität zentral, weil veraltete Ergebnisse den Informationsbedarf nicht erfüllen. Deshalb kann dasselbe Signal je nach Anfrage unterschiedlich stark gewichtet werden.',criteria:['Du unterscheidest zeitlos und aktuell.','Du stellst den Bezug zur Suchabsicht her.','Du erklärst die unterschiedliche Gewichtung.']}),
      T('rank-bonus','ranking','Bonus: Fairer Kriterienmix','free','Entwirf für eine vereinfachte Klassenzimmer-Suchmaschine vier Kriterien für das Ranking von Produktseiten. Begründe, warum kein einzelnes Kriterium allein ausreichen sollte.',50,{bonus:true,placeholder:'Nenne vier Kriterien und begründe den Kriterienmix.',solution:'Beispiel: Passung zur Suchanfrage, Informationsgehalt, Aktualität relevanter Angaben und technische Nutzbarkeit. Ein einzelnes Kriterium wäre leicht verzerrbar: Häufige Keyword-Nennung sagt etwa wenig über Qualität aus. Mehrere Kriterien können unterschiedliche Aspekte der Nützlichkeit abbilden.',criteria:['Du nennst vier nachvollziehbare Kriterien.','Du begründest jedes oder den Mix insgesamt.','Du erklärst ein Risiko eines Einzelkriteriums.']})
    ]
  },
  {
    id:'seo', nav:'SEO', icon:'📈', title:'SEO: Wie verbessert UrbanStep seine Auffindbarkeit?', kicker:'Best Practices statt Tricks – mit realen Unternehmensbeispielen',
    content:`
      <div class="definition-card"><div class="definition-label">Definition · SEO</div><p><strong>Search Engine Optimization (SEO)</strong> bezeichnet Maßnahmen, mit denen Webseiten technisch und inhaltlich so verbessert werden, dass Suchmaschinen Inhalte gut <strong>finden, verstehen und bei passenden Suchanfragen berücksichtigen</strong> können.</p></div>
      <div class="seo-pillars">
        <div><span>🕷️</span><h4>Auffindbar</h4><p>klare interne Links, Sitemap, öffentlich erreichbare Seiten</p></div>
        <div><span>🧠</span><h4>Verständlich</h4><p>aussagekräftige Titel, Überschriften, echte Produktinformationen, strukturierte Daten</p></div>
        <div><span>✨</span><h4>Nützlich</h4><p>hilfreicher Inhalt, gute mobile Nutzung, schnelle und zuverlässige Seite</p></div>
      </div>
      <div class="definition-card"><div class="definition-label">Definition · strukturierte Daten</div><p><strong>Strukturierte Daten</strong> sind maschinenlesbare Angaben, mit denen eine Website die Bedeutung ihrer Inhalte expliziter kennzeichnen kann. Für Produkte können z. B. <strong>Preis, Verfügbarkeit, Bewertungen sowie Versand- oder Rückgabeinformationen</strong> ausgezeichnet werden.</p></div>
      <div class="code-demo"><div class="code-head">Vereinfachtes Produkt-Markup</div><pre>{
  "@type": "Product",
  "name": "RainStep One",
  "offers": {
    "price": "89.90",
    "priceCurrency": "EUR",
    "availability": "InStock"
  }
}</pre><p>Die Darstellung ist vereinfacht. Strukturierte Daten können Suchmaschinen zusätzliche Hinweise geben, garantieren aber <strong>weder ein Rich Result noch eine bestimmte Rankingposition</strong>.</p></div>
      <div class="best-practice-grid">
        <div><span>🔗</span><b>Interne Verlinkung</b><p>Wichtige Seiten von erreichbaren Kategorien aus verlinken.</p></div>
        <div><span>🗺️</span><b>Sitemap</b><p>Neue und wichtige URLs strukturiert melden.</p></div>
        <div><span>🏷️</span><b>Klare Seitentitel</b><p>Produkt und Inhalt präzise beschreiben statt nur Werbeslogans.</p></div>
        <div><span>📝</span><b>Hilfreicher Inhalt</b><p>Eigenschaften, Größen, Materialien, Pflege, Fragen beantworten.</p></div>
        <div><span>📱</span><b>Mobile Qualität</b><p>Auf Smartphones schnell, lesbar und bedienbar bleiben.</p></div>
        <div><span>⚙️</span><b>Technik</b><p>Fehler vermeiden, sinnvolle URLs und indexierbare Seiten bereitstellen.</p></div>
      </div>
      <h3 class="section-subtitle">SEO in der realen Welt</h3>
      <div class="case-study-grid">
        <div class="case-study"><div class="metric">+15%</div><h4>Saramin</h4><p>Die koreanische Jobplattform behob zunächst Crawling-Fehler und verbesserte die technische Auffindbarkeit. Google dokumentiert bereits nach diesen ersten Arbeiten einen <strong>15%igen Anstieg des organischen Traffics</strong>. In der Haupteinstellungsphase 2019 lag der organische Google-Traffic im Jahresvergleich <strong>102% höher</strong>.</p><a href="https://developers.google.com/search/case-studies/saramin-case-study?hl=de" target="_blank" rel="noopener">Fallstudie öffnen</a></div>
        <div class="case-study"><div class="metric">+94%</div><h4>Monster India</h4><p>Monster India führte strukturierte <strong>JobPosting</strong>-Daten ein. Google dokumentiert für Jobdetailseiten einen <strong>94%igen Anstieg des organischen Traffics</strong> und <strong>10% mehr Bewerbungen</strong>.</p><a href="https://developers.google.com/search/case-studies/monster-india-case-study?hl=de" target="_blank" rel="noopener">Fallstudie öffnen</a></div>
        <div class="case-study"><div class="metric">2,7×</div><h4>Rakuten Recipe</h4><p>Rakuten verbesserte strukturierte Rezeptdaten und deren technische Qualität. Laut Google stieg der Traffic aus Suchmaschinen auf den Rezeptseiten auf das <strong>2,7-Fache</strong>; die durchschnittliche Sitzungsdauer auf das <strong>1,5-Fache</strong>.</p><a href="https://developers.google.com/search/case-studies/rakuten-case-study?hl=de" target="_blank" rel="noopener">Fallstudie öffnen</a></div>
      </div>
      <div class="warning-note"><strong>Fallstudien sind keine Garantie.</strong> Die Ergebnisse gelten für konkrete Unternehmen, Zeiträume und Maßnahmen. Aus „Monster India +94%“ darf man nicht ableiten, dass strukturierte Daten jeder Website automatisch +94% Traffic bringen.</div>
      <div class="source-row"><a class="source-link" href="https://developers.google.com/search/docs/fundamentals/seo-starter-guide?hl=de" target="_blank" rel="noopener">📚 SEO-Starter-Guide</a><a class="source-link" href="https://developers.google.com/search/docs/appearance/structured-data/product-snippet?hl=de" target="_blank" rel="noopener">📚 Strukturierte Produktdaten</a></div>`,
    tasks:[
      T('seo-1','seo','SEO definieren','single','Welche Beschreibung trifft SEO am besten?',20,{options:[['a','Bezahlte Werbeplätze kaufen'],['b','Webseiten technisch und inhaltlich suchfreundlich verbessern'],['c','Suchmaschinen hacken'],['d','Nur möglichst viele Keywords wiederholen']],correct:'b',solution:'SEO verbessert Webseiten technisch und inhaltlich für Auffindbarkeit, Verständnis und passende Suchanfragen.',explanation:'Seriöse SEO ist keine Garantie auf eine Position, sondern systematische Qualitäts- und Auffindbarkeitsarbeit.'}),
      T('seo-2','seo','Strukturierte Daten','boolean','Strukturierte Produktdaten können zusätzliche Hinweise zu Preis oder Verfügbarkeit geben, garantieren aber weder Rich Results noch Platz 1.',20,{correct:true,solution:'Richtig.',explanation:'Markup kann Suchsystemen helfen, Inhalte zu verstehen, aber die Darstellung und das Ranking bleiben von weiteren Bedingungen abhängig.'}),
      T('seo-3','seo','Maßnahme und Ziel','matching','Ordne die SEO-Maßnahme ihrem Hauptziel zu.',30,{pairs:[['Produktseite intern verlinken','Auffindbarkeit verbessern'],['Produktname klar im Titel nennen','Inhalt verständlicher machen'],['Mobile Ladeprobleme beheben','Nutzerfreundlichkeit/Technik verbessern'],['Product-Markup ergänzen','Bedeutung von Produktinformationen maschinenlesbar kennzeichnen']],solution:'Link → Auffindbarkeit; klarer Titel → Verständnis; mobile Technik → Nutzerfreundlichkeit; strukturierte Daten → maschinenlesbare Bedeutung.',explanation:'SEO wirkt an mehreren Stellen des Suchprozesses.'}),
      T('seo-4','seo','UrbanSteps Produktseite','multi','Welche Maßnahmen sind sinnvolle Best Practices für die RainStep-One-Seite?',30,{options:[['a','Produktseite von der Sneaker-Kategorie verlinken'],['b','Aussagekräftigen Titel und hilfreiche Produktinformationen verwenden'],['c','Unsichtbar tausende Keywords verstecken'],['d','Mobile Bedienbarkeit und Ladeverhalten verbessern'],['e','Passende strukturierte Produktdaten korrekt auszeichnen']],correct:['a','b','d','e'],solution:'Sinnvoll sind a, b, d und e.',explanation:'Diese Maßnahmen unterstützen Auffindbarkeit, Verständnis und Nutzbarkeit; versteckte Keyword-Manipulation ist keine saubere Best Practice.'}),
      T('seo-5','seo','Reale Fallstudien','matching','Ordne die dokumentierte Maßnahme dem Unternehmen zu.',30,{pairs:[['Crawling-Fehler beheben und Search Console nutzen','Saramin'],['JobPosting-Strukturdaten einführen','Monster India'],['Rezept-Strukturdaten verbessern und validieren','Rakuten Recipe']],solution:'Saramin → Crawling/technische SEO; Monster India → JobPosting; Rakuten Recipe → Rezept-Strukturdaten.',explanation:'Die Beispiele zeigen unterschiedliche SEO-Hebel aus realen Google-Fallstudien.'}),
      T('seo-6','seo','SEO-Prioritäten','order','UrbanStep hat eine neue Seite, die noch kaum gefunden wird. Sortiere eine sinnvolle Arbeitsreihenfolge.',30,{items:[['a','Hilfreiche Produktinformationen und klare Seitentitel verbessern'],['b','Prüfen, ob die Seite öffentlich erreichbar und intern verlinkt ist'],['c','Optionale strukturierte Produktdaten korrekt ergänzen'],['d','Mobile Technik und Ladeprobleme prüfen']],correct:['b','a','d','c'],solution:'Erreichbarkeit/Verlinkung → Inhalt → technische Nutzerfreundlichkeit → zusätzliche strukturierte Daten.',explanation:'Zuerst müssen grundlegende Auffindbarkeit und Inhalt stimmen; Zusatzmarkups bauen darauf auf.'}),
      T('seo-7','seo','Fallstudie korrekt interpretieren','free','Ein Anbieter wirbt: „Mit strukturierten Daten steigt euer Traffic garantiert um 94%, wie bei Monster India.“ Beurteile diese Aussage.',40,{placeholder:'Nutze den Unterschied zwischen Fallstudie und allgemeiner Garantie.',solution:'Die Aussage ist nicht zulässig. Monster India verzeichnete in einer konkreten Fallstudie nach Einführung von JobPosting-Markup einen 94%igen Anstieg des organischen Traffics auf Jobdetailseiten. Das Ergebnis hängt von Ausgangslage, Branche, Umsetzung, Suchangebot und weiteren Faktoren ab und kann nicht als Garantie auf andere Websites übertragen werden.',criteria:['Du nennst den konkreten Fallbezug.','Du lehnt die pauschale Garantie ab.','Du erklärst, warum Ergebnisse nicht 1:1 übertragbar sind.']}),
      T('seo-8','seo','UrbanStep SEO-Mini-Audit','free','Führe ein Mini-Audit der fiktiven RainStep-Seite durch: Nenne jeweils eine konkrete Verbesserung für Auffindbarkeit, Verständlichkeit und Nutzerfreundlichkeit und erkläre die Wirkung.',40,{placeholder:'Drei Maßnahmen: eine für Auffindbarkeit, eine für Inhalt/Verständlichkeit, eine für Technik/Nutzung.',solution:'Beispiel: Auffindbarkeit – die Produktseite von der Sneaker-Kategorie verlinken und in die Sitemap aufnehmen. Verständlichkeit – einen präzisen Titel sowie echte Informationen zu Wasserdichtigkeit, Materialien, Größen und Pflege ergänzen. Nutzerfreundlichkeit – mobile Ladezeit und Bedienbarkeit prüfen. Jede Maßnahme wirkt an einer anderen Stelle des Suchprozesses.',criteria:['Du nennst drei konkrete Maßnahmen.','Die Maßnahmen decken drei unterschiedliche Bereiche ab.','Du erklärst die jeweilige Wirkung.']}),
      T('seo-bonus','seo','Bonus: Product-Markup','free','Welche Produktinformationen wären für korrektes strukturiertes Markup beim RainStep One besonders plausibel? Nenne mindestens vier und erkläre, warum falsche Angaben problematisch wären.',50,{bonus:true,placeholder:'Nenne mindestens vier plausible Produktangaben und erkläre die Bedeutung korrekter Daten.',solution:'Plausibel sind z. B. Produktname, Preis, Währung, Verfügbarkeit, Bewertung, Versand- oder Rückgabeinformationen. Strukturierte Daten sollten den sichtbaren und tatsächlichen Inhalt korrekt wiedergeben; erfundene oder widersprüchliche Angaben wären irreführend und können die Verarbeitung beeinträchtigen.',criteria:['Du nennst mindestens vier passende Angaben.','Du betonst die Übereinstimmung mit realen sichtbaren Daten.','Du erklärst das Problem falscher Angaben.']})
    ]
  },
  {
    id:'finale', nav:'Finale', icon:'🚀', title:'Finale: UrbanSteps Search-Launch-Plan', kicker:'Den gesamten Suchmaschinenprozess anwenden und beurteilen',
    content:`
      <div class="hero-case final-mission"><img class="hero-illustration" src="/assets/launch.svg" alt="Illustration eines erfolgreichen Produktlaunches"><div><span class="eyebrow">Abschlussmission</span><h3>Der RainStep One geht live</h3><p>UrbanStep möchte die Produktseite veröffentlichen und organisch auffindbar machen. Du kennst nun den Weg von der <strong>Entdeckung</strong> über die <strong>Indexierung</strong> bis zur <strong>Relevanzbewertung und zum Ranking</strong>.</p></div></div>
      <div class="flow-diagram big final-flow"><div class="flow-node">1 · Produktseite<br><small>öffentlich & verlinkt</small></div><div class="flow-arrow">→</div><div class="flow-node">2 · Crawling<br><small>Googlebot entdeckt URL</small></div><div class="flow-arrow">→</div><div class="flow-node">3 · Indexierung<br><small>Inhalt verstehen</small></div><div class="flow-arrow">→</div><div class="flow-node">4 · Suchanfrage<br><small>Passung ermitteln</small></div><div class="flow-arrow">→</div><div class="flow-node">5 · Ranking<br><small>Ergebnisse ordnen</small></div></div>
      <div class="myth-grid">
        <div class="myth"><span>❌</span><b>„Mehr Crawling = automatisch höheres Ranking.“</b><p>Falsch. Häufigeres Crawling ist nicht gleichbedeutend mit höherer Relevanz.</p></div>
        <div class="myth"><span>❌</span><b>„Jede gecrawlte Seite wird garantiert indexiert.“</b><p>Falsch. Crawling und Indexierung sind getrennte Schritte.</p></div>
        <div class="myth"><span>❌</span><b>„Eine SEO-Maßnahme garantiert Platz 1.“</b><p>Falsch. Rankings beruhen auf vielen Signalen und Konkurrenzsituationen.</p></div>
        <div class="myth"><span>✅</span><b>„Gute SEO beginnt bei Nutzern und Technik.“</b><p>Richtig: auffindbar, verständlich, hilfreich und technisch sauber.</p></div>
      </div>
      <div class="definition-card"><div class="definition-label">Gesamtmerksatz</div><p>Eine Suchmaschine <strong>entdeckt</strong> Seiten durch Crawling, <strong>verarbeitet</strong> sie für einen Index und wählt bei einer Suchanfrage passende Inhalte aus. Das <strong>Ranking</strong> ordnet diese Ergebnisse anhand vieler Signale. SEO kann Auffindbarkeit, Verständlichkeit und Nutzbarkeit verbessern – eine bestimmte Position lässt sich jedoch nicht seriös garantieren.</p></div>
      <div class="source-row"><a class="source-link" href="https://developers.google.com/search/docs/fundamentals/how-search-works?hl=de" target="_blank" rel="noopener">📚 Gesamtüberblick Google Search Central</a><a class="source-link" href="https://developers.google.com/search/docs/fundamentals/seo-starter-guide?hl=de" target="_blank" rel="noopener">📚 SEO-Starter-Guide</a></div>`,
    tasks:[
      T('final-1','finale','Gesamtprozess','single','Welcher Prozess ist fachlich korrekt?',20,{options:[['a','SEO → Anzeige kaufen → Index löschen'],['b','Crawling → Indexierung → Relevanz/Ranking bei Suchanfrage'],['c','Ranking → Sitemap → Crawling'],['d','Scraping → Werbung → Verschlüsselung']],correct:'b',solution:'Crawling → Indexierung → Relevanz/Ranking bei Suchanfrage.',explanation:'Diese Kette bildet den Kern der Funktionsweise einer Suchmaschine.'}),
      T('final-2','finale','Mythos: mehr Crawling','boolean','Wenn UrbanStep Googlebot dazu bringt, die Produktseite häufiger abzurufen, steigt die Seite allein dadurch automatisch im Ranking.',20,{correct:false,solution:'Falsch.',explanation:'Crawling-Häufigkeit ist nicht automatisch ein Rankingvorteil. Sie betrifft zunächst das Abrufen von Inhalten.'}),
      T('final-3','finale','Maßnahmen einordnen','matching','Ordne die Maßnahme der Stelle zu, an der sie hauptsächlich ansetzt.',30,{pairs:[['Interne Links zur Produktseite','Crawling/Auffindbarkeit'],['Klare Produktinformationen','Indexierung/Verständnis + Relevanz'],['Mobile Ladeprobleme beheben','Nutzerfreundlichkeit/Technik'],['Suchabsicht der Zielgruppe analysieren','Inhaltliche Relevanz']],solution:'Links → Auffindbarkeit; Produktinformationen → Verständnis/Relevanz; mobile Technik → Nutzbarkeit; Suchabsicht → relevante Inhalte.',explanation:'SEO ist ein Bündel unterschiedlicher Maßnahmen entlang des gesamten Suchprozesses.'}),
      T('final-4','finale','Launch-Ablauf','order','Bringe UrbanSteps Search-Launch in eine sinnvolle Reihenfolge.',30,{items:[['a','Suchanfragen und Suchabsichten analysieren, Inhalte verbessern'],['b','Produktseite veröffentlichen und intern verlinken'],['c','Technische Fehler und mobile Nutzung prüfen'],['d','Ergebnisse über Search Console und reale Suchanfragen beobachten'],['e','Optionale strukturierte Produktdaten ergänzen']],correct:['b','a','c','e','d'],solution:'Veröffentlichen/Verlinken → relevante Inhalte → Technik → strukturierte Daten → beobachten und verbessern.',explanation:'SEO ist ein kontinuierlicher Prozess; nach dem Launch werden Daten geprüft und Verbesserungen iterativ vorgenommen.'}),
      T('final-5','finale','Fachbegriffe im Fall','multi','Welche Aussagen zum RainStep-One-Fall sind korrekt?',30,{options:[['a','Googlebot kann die Seite über Links entdecken.'],['b','Der Index wird erst nach jeder einzelnen Suchanfrage komplett neu gebaut.'],['c','Strukturierte Daten können Produktinformationen maschinenlesbar kennzeichnen.'],['d','Ranking beschreibt die Reihenfolge der Ergebnisse.'],['e','Web Scraping und Crawling bedeuten immer exakt dasselbe.']],correct:['a','c','d'],solution:'Richtig sind a, c und d.',explanation:'Indexierung wird vorbereitet; Crawling und Scraping sind unterschiedliche Konzepte.'}),
      T('final-6','finale','Fehlerdiagnose','multi','UrbanStep wird kaum gefunden. Welche Prüfungen sind sinnvoll?',30,{options:[['a','Ist die Seite öffentlich erreichbar und nicht versehentlich blockiert?'],['b','Gibt es interne Links/Sitemap-Hinweise?'],['c','Beschreibt der Inhalt das Produkt klar und passend zur Zielgruppe?'],['d','Funktioniert die Seite mobil und technisch zuverlässig?'],['e','Kann UrbanStep ein organisches Top-Ranking direkt kaufen?']],correct:['a','b','c','d'],solution:'Sinnvoll sind a, b, c und d.',explanation:'Die Ursachen können bei Erreichbarkeit, Crawling, Inhalt, Indexierung oder technischer Nutzerfreundlichkeit liegen.'}),
      T('final-7','finale','Search-Launch-Plan','free','Erstelle für UrbanStep einen Search-Launch-Plan mit mindestens sechs konkreten Maßnahmen. Ordne jede Maßnahme einem Bereich zu: Crawling, Indexierung, Relevanz/Ranking oder SEO-Technik.',40,{placeholder:'Mindestens sechs Maßnahmen mit kurzer Zuordnung und Begründung.',solution:'Beispiel: 1) Produktseite intern verlinken (Crawling); 2) Sitemap aktualisieren (Crawling); 3) klare Titel/Überschriften und echte Produktinformationen bereitstellen (Indexierung/Relevanz); 4) doppelte Produkt-URLs vermeiden bzw. kanonische Version klären (Indexierung); 5) mobile Lade- und Bedienprobleme beheben (SEO-Technik); 6) strukturierte Product-Daten korrekt ergänzen (Verständnis/Darstellung); 7) Suchabsichten analysieren und Inhalte daran ausrichten (Relevanz); 8) Search Console zur Kontrolle technischer Probleme nutzen.',criteria:['Du nennst mindestens sechs konkrete Maßnahmen.','Du ordnest jede Maßnahme einem passenden Bereich zu.','Du begründest die Wirkung nachvollziehbar.']}),
      T('final-8','finale','Erklären wie ein Profi','free','Erkläre einer Person ohne Informatikkenntnisse in einem zusammenhängenden Text, wie aus UrbanSteps neuer Produktseite ein mögliches Google-Suchergebnis wird.',40,{placeholder:'Schreibe einen zusammenhängenden Erklärtext mit den Fachbegriffen Crawling, Indexierung, Index, Relevanz und Ranking.',solution:'Googlebot kann die neue UrbanStep-Seite beispielsweise über interne Links oder eine Sitemap entdecken und crawlen. Danach analysiert Google die Inhalte bei der Indexierung und organisiert Informationen im Suchindex. Wenn jemand eine Suchanfrage stellt, werden passende Inhalte aus dem Index ausgewählt. Die Relevanz beschreibt die Passung zum Informationsbedarf; Rankingsysteme ordnen die geeigneten Ergebnisse anhand vieler Signale. SEO kann helfen, die Seite auffindbar, verständlich und nutzerfreundlich zu gestalten, garantiert aber keine bestimmte Position.',criteria:['Du verwendest alle fünf geforderten Fachbegriffe korrekt.','Du beschreibst die Prozessreihenfolge.','Du erklärst die Rolle von SEO ohne Ranking-Garantie.']}),
      T('final-bonus','finale','Bonus: Vorstandspitch','free','Die Geschäftsführung fragt: „Warum sollten wir in SEO investieren, wenn es keine Platz-1-Garantie gibt?“ Formuliere eine sachliche Antwort mit mindestens drei Nutzenargumenten und einer klaren Einschränkung.',50,{bonus:true,placeholder:'Formuliere eine kurze, sachliche Argumentation für eine Geschäftsführung.',solution:'SEO kann die technische Auffindbarkeit verbessern, Inhalte für Suchmaschinen und Nutzer verständlicher machen und die Nutzererfahrung auf mobilen Geräten stärken. Reale Fallstudien zeigen, dass solche Maßnahmen unter passenden Bedingungen erheblichen organischen Traffic und Conversions unterstützen können. Gleichzeitig gibt es keine Garantie für eine bestimmte Rankingposition oder einen festen Traffic-Zuwachs, weil Ergebnisse von vielen Faktoren, Konkurrenz und Ausgangslage abhängen.',criteria:['Du nennst mindestens drei Nutzenargumente.','Du stellst einen wirtschaftlichen Bezug her.','Du formulierst ausdrücklich eine Grenze bzw. fehlende Garantie.']})
    ]
  }
];

export const ALL_TASKS = SECTIONS.flatMap(s=>s.tasks);
export const TASK_XP = Object.fromEntries(ALL_TASKS.map(t=>[t.id,t.xp]));
export const CORE_TASK_IDS = ALL_TASKS.filter(t=>!t.bonus).map(t=>t.id);
export const MAX_XP = ALL_TASKS.reduce((sum,t)=>sum+t.xp,0);
